export interface TimeslotData {
  date:                  string, // YYYY-MM-DD
  color?:                string, // For visualization in frontend
  startTime:             string, // HH24:MM
  endTime:               string, // HH24:MM
  period:                string,
  type?:                 string, // For filtering in frontend
  fromSchedule?:         string, // If generated by a schedule
  fromScheduleName?:     string, // If generated by a schedule
  description?:          string, // Free text field for individual timeslot
  contact?:              string, // For info
  assistantSlots:        Array<string>, // Array of slots in increasing assistant level
  // Booking data
  assistantAllocations:  Array<string>, // Array of allocated in increasing assistant level
  acceptedBookings:      Array<string>, // List of accepted bookings (id)
}

export interface Timeslot extends TimeslotData {
  id: string
}

export const EMPTY_TIMESLOT = {
  id:                   "",
  date:                 "",
  startTime:            "",
  endTime:              "",
  period:               "",
  assistantSlots:       [],
  assistantAllocations: [],
  acceptedBookings:     [],
};
