// export interface AssistantSlot {
//   type: string, //  Type of assistants (in this slot)
//   number: number, // Number of assistants of Type
// }

export interface TimeslotData {
  date: string, // YYYY-MM-DD
  startDatetime: string, // YYYY-MM-DD HH24:MM:SS
  endDatetime: string, // YYYY-MM-DD HH24:MM:SS
  period: string,
  fromSchedule?: string, // If generated by a schedule
  description?: string, // Free text field for individual timeslot
  color?: string, // For visualization in frontend
  type?: string, // For filtering in frontend
  contact?: string, // For info
  assistantSlots: Array<number>, // Array of slots (number) in increasing assistant level
}

    // "date": "2022-09-14",
    // "startDatetime": "2022-09-14 17:00",
    // "endDatetime": "2022-09-14 21:00",
    // "timeDesc": "08:00-12:30",
    // "period": "Pj8G1ETxJZhv1B4wogAh",
    // "fromSchedule": "1",
    // "description": "...",
    // "color": "blue",
    // "type": "Scheduled",
    // "contact": "",
    // "assistantSlots": [ "1", "2", "3"]

  // date: string, // 
  // startDatetime: number,
  // endDatetime: number,
  // timeDesc?: string, // I.e. 08:00-12:30
  // period: string,
  // fromSchedule?: string, // If generated by a schedule
  // description?: string, // Free text field for individual timeslot
  // color?: string, // For visualization in frontend
  // type?: string, // For filtering in frontend
  // contact?: string, // For info
  // assistantSlots: <AssistantSlot>, // Map array of AssistantSlots

export interface Timeslot extends TimeslotData {
  id: string
}