import * as functions from "firebase-functions";
// import * as admin from "firebase-admin";
import * as express   from "express";
import {routes}       from "./routes";
import {authenticate} from "./utils/useAuth";
import * as cors      from "cors";

// Express CORS
const app = express();
app.use(cors());

// Express authentication middleware
app.use(authenticate);

// Add all routes
app.use("/", routes);

// Expose API as a function
exports.api = functions.https.onRequest(app);

// ------------------
// Booking processing
// ------------------
// DB trigger or part of booking endpoints?
// export interface TimeslotData {
//   date:              string, // YYYY-MM-DD
//   color?:            string, // For visualization in frontend
//   startTime:         string, // HH24:MM
//   endTime:           string, // HH24:MM
//   period:            string,
//   type?:             string, // For filtering in frontend
//   fromSchedule?:     string, // If generated by a schedule
//   fromScheduleName?: string, // If generated by a schedule
//   description?:      string, // Free text field for individual timeslot
//   contact?:          string, // For info
//   assistantSlots:    Array<string>, // Array of slots (number) in increasing assistant level
// // Booking data
//   assistantFilled?:  Array<string>, // Array of filled (number of slots) in increasing assistant level
//   acceptedBookings?: Array<string>, // List of accepted bookings (id)
// }
