import {Router} from "express";
import * as functions from "firebase-functions";
import {getUserid, isUseridAdmin} from "../utils/useAuth"
import {timeslotsCol} from '../utils/useDb'
import {Timeslot, TimeslotData} from "../types/Timeslot"
//import {PeriodData} from "../types/Period"

const timeslotRoute = Router();

// -------------
// GET TIMTESLOT
// -------------
timeslotRoute.get("/timeslot/:timeslotid", async (req, res) => {
  const docId: string = req.params.timeslotid

  const timeslotDoc = await timeslotsCol.doc(docId).get();
  if (timeslotDoc.exists) {
    const timeslotData: TimeslotData = timeslotDoc.data()!;
    return res.status(200).json({ id: docId, ...timeslotData });
  }

  return res.status(200).json({ });
});

// ------------------
// GET ALL TIMTESLOTS
// ------------------
timeslotRoute.get("/timeslots", async (req, res) => {
  const resTimeslots: Array<Timeslot>  = [];

  const timeslotDocs =
    await timeslotsCol.orderBy("startDatetime").get();

  timeslotDocs.forEach((doc: FirebaseFirestore.DocumentData) => {
    resTimeslots.push({ id: doc.id, ...doc.data() });
  });
  
  return res.status(200).json(resTimeslots);
});

// -------------
// POST TIMESLOT
// -------------
timeslotRoute.post("/timeslot", async (req, res) => {
  // TODO - error handling in getUserid
  const userid = getUserid(req);

  const isAdmin: boolean = await isUseridAdmin(userid);
  if (!isAdmin) {
    return res.status(403).json("Not allowed for non-admin");
  }

  // name: string, // 
  // startDatetime: string, // YYYY-MM-DD HH24:MM:SS
  // endDatetime: string, // YYYY-MM-DD HH24:MM:SS
  // durationInHours: number, // I.e. 4,5
  // timeDesc?: string, // I.e. 08:00-12:30
  // weekday: string,
  // period: string,
  // fromSchedule?: string, // If generated by a schedule
  // description?: string, // Free text field for individual timeslot
  // color?: string, // For visualization in frontend
  // type?: string, // For filtering in frontend
  // contact?: string, // For info
  // assistantSlots: Map<String, String>, // Map array of AssistantSlots

  if(!req.body.name ||
     !req.body.startDatetime ||
     !req.body.endDatetime ||
     !req.body.durationInHours ||
     !req.body.weekday ||
     !req.body.period ||
     !req.body.assistantSlots)
  {
    return res.status(400).send(
      "Incorrect body.\n Correct syntax is: { \"name\": ..., \"startDatetime\": ..., \"endDatetime\": ..., \"durationInHours\": ..., \"timedesc\": ..., \"weekday\": ..., \"period\": ... \"assistantSlots\": ...}");
  }

  // TODO - Unique constraint check?

  let docId: string = '' // Set from res.id
  let timeslotData: TimeslotData = {
  name: req.body.name,
  startDatetime: req.body.startDatetime,
  endDatetime: req.body.endDatetime,
  durationInHours: req.body.durationInHours,
  weekday: req.body.weekday,
  period: req.body.period,
  assistantSlots: req.body.assistantSlots,
  };

  if (req.body.timeDesc) { timeslotData.timeDesc = req.body.timeDesc; }
  if (req.body.fromSchedule) { timeslotData.fromSchedule = req.body.fromSchedule; }
  if (req.body.description) { timeslotData.description = req.body.description; }
  if (req.body.contact) { timeslotData.contact = req.body.contact; }
  if (req.body.color) { timeslotData.color = req.body.color; }
  if (req.body.type) { timeslotData.type = req.body.type; }

  functions.logger.log("POST /timeslot by " + userid, timeslotData);
  const docRes = await timeslotsCol.add(timeslotData);
  docId = docRes.id;

  return res.status(200).json({
    id: docId,
    ...timeslotData
  });
});

// -------------
// PUT TIMESLOT
// -------------
timeslotRoute.put("/timeslot/:timeslotid", async (req, res) => {
  // TODO - error handling in getUserid
  const userid = getUserid(req);

  const isAdmin: boolean = await isUseridAdmin(userid);
  if (!isAdmin) {
    return res.status(403).json("Not allowed for non-admin");
  }

  if(!req.body.name ||
     !req.body.startDatetime ||
     !req.body.endDatetime ||
     !req.body.durationInHours ||
     !req.body.weekday ||
     !req.body.period ||
     !req.body.assistantSlots)
  {
    return res.status(400).send(
      "Incorrect body.\n Correct syntax is: { \"name\": ..., \"startDatetime\": ..., \"endDatetime\": ..., \"durationInHours\": ..., \"timedesc\": ..., \"weekday\": ..., \"period\": ... \"assistantSlots\": ...}");
  }

  // TODO - Unique constraint check?

  let docId: string = req.params.timeslotid
  let timeslotData: TimeslotData = {
  name: req.body.name,
  startDatetime: req.body.startDatetime,
  endDatetime: req.body.endDatetime,
  durationInHours: req.body.durationInHours,
  weekday: req.body.weekday,
  period: req.body.period,
  assistantSlots: req.body.assistantSlots,
  };

  if (req.body.timeDesc) { timeslotData.timeDesc = req.body.timeDesc; }
  if (req.body.fromSchedule) { timeslotData.fromSchedule = req.body.fromSchedule; }
  if (req.body.description) { timeslotData.description = req.body.description; }
  if (req.body.contact) { timeslotData.contact = req.body.contact; }
  if (req.body.color) { timeslotData.color = req.body.color; }
  if (req.body.type) { timeslotData.type = req.body.type; }

  functions.logger.log("PUT /timeslot by " + userid, timeslotData);
  await timeslotsCol.doc(docId).set(timeslotData);

  return res.status(200).json({
    id: docId,
    ...timeslotData
  });
});

// ---------------
// DELETE TIMESLOT
// ---------------
timeslotRoute.delete("/timeslot/:timeslotid", async (req, res) => {
  const docId: string = req.params.timeslotid;

  const userid = getUserid(req);

  const isAdmin: boolean = await isUseridAdmin(userid);
  if (!isAdmin) {
    return res.status(403).json("Not allowed for non-admin");
  }

  await timeslotsCol.doc(docId).delete();

  return res.status(200).json({ });
});

export {timeslotRoute};
